Repository Semoban/meongcare-back, pull requests merged in 2023-11, with the labels that each got.

#3 feat: 소셜 로그인 구현
  meongcare/.gitignore
  meongcare/build.gradle
  meongcare/src/main/java/com/meongcare/auth/domain/repository/MemberRepository.java
  meongcare/src/main/java/com/meongcare/common/jwt/JwtService.java
  meongcare/src/main/java/com/meongcare/common/jwt/JwtValidateArgumentResolver.java
  meongcare/src/main/java/com/meongcare/common/jwt/JwtValidation.java
  meongcare/src/main/java/com/meongcare/dog/domain/DogRepository.java
  meongcare/src/main/java/com/meongcare/domain/auth/domain/entity/Member.java
  meongcare/src/main/java/com/meongcare/domain/auth/domain/entity/Provider.java
  meongcare/src/main/java/com/meongcare/domain/auth/domain/entity/RefreshToken.java
  meongcare/src/main/java/com/meongcare/domain/auth/domain/repository/MemberRepository.java
  meongcare/src/main/java/com/meongcare/domain/auth/domain/repository/RefreshTokenRedisRepository.java
  meongcare/src/main/java/com/meongcare/domain/auth/presentation/controller/AuthController.java
  meongcare/src/main/java/com/meongcare/domain/auth/presentation/dto/request/LoginRequestDto.java
  meongcare/src/main/java/com/meongcare/domain/auth/presentation/dto/response/LoginResponseDto.java
  meongcare/src/main/java/com/meongcare/domain/auth/presentation/dto/response/ReissueResponseDto.java
  meongcare/src/main/java/com/meongcare/domain/auth/service/AuthService.java
  meongcare/src/main/java/com/meongcare/domain/dog/domain/DogRepository.java
  meongcare/src/main/java/com/meongcare/domain/dog/domain/DogWeightRepository.java
  meongcare/src/main/java/com/meongcare/domain/dog/domain/entity/Dog.java
  meongcare/src/main/java/com/meongcare/domain/dog/domain/entity/DogWeight.java
  meongcare/src/main/java/com/meongcare/domain/dog/presentation/controller/DogController.java
  meongcare/src/main/java/com/meongcare/domain/dog/presentation/dto/request/SaveDogRequestDto.java
  meongcare/src/main/java/com/meongcare/domain/dog/service/DogService.java
  meongcare/src/main/java/com/meongcare/infra/config/RedisConfig.java
  meongcare/src/main/java/com/meongcare/infra/config/WebConfig.java
  meongcare/src/main/resources/application-example.yml
  meongcare/src/main/resources/application.yml
Labels: feat

#4 feat: 대소변, 이상증상 API
  meongcare/build.gradle
  meongcare/src/main/java/com/meongcare/MeongcareApplication.java
  meongcare/src/main/java/com/meongcare/common/BaseEntity.java
  meongcare/src/main/java/com/meongcare/common/DateTimePattern.java
  meongcare/src/main/java/com/meongcare/common/util/LocalDateTimeUtils.java
  meongcare/src/main/java/com/meongcare/domain/dog/domain/DogRepository.java
  meongcare/src/main/java/com/meongcare/domain/excreta/application/ExcretaService.java
  meongcare/src/main/java/com/meongcare/domain/excreta/domain/entity/Excreta.java
  meongcare/src/main/java/com/meongcare/domain/excreta/domain/entity/ExcretaType.java
  meongcare/src/main/java/com/meongcare/domain/excreta/domain/repository/ExcretaQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/excreta/domain/repository/ExcretaRepository.java
  meongcare/src/main/java/com/meongcare/domain/excreta/domain/repository/vo/GetExcretaVO.java
  meongcare/src/main/java/com/meongcare/domain/excreta/presentation/ExcretaController.java
  meongcare/src/main/java/com/meongcare/domain/excreta/presentation/dto/request/DeleteExcretaRequest.java
  meongcare/src/main/java/com/meongcare/domain/excreta/presentation/dto/request/PatchExcretaRequest.java
  meongcare/src/main/java/com/meongcare/domain/excreta/presentation/dto/request/SaveExcretaRequest.java
  meongcare/src/main/java/com/meongcare/domain/excreta/presentation/dto/response/GetExcretaResponse.java
  meongcare/src/main/java/com/meongcare/domain/symptom/application/SymptomService.java
  meongcare/src/main/java/com/meongcare/domain/symptom/domain/entity/Symptom.java
  meongcare/src/main/java/com/meongcare/domain/symptom/domain/entity/SymptomType.java
  meongcare/src/main/java/com/meongcare/domain/symptom/domain/repository/SymptomQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/symptom/domain/repository/SymptomRepository.java
  meongcare/src/main/java/com/meongcare/domain/symptom/domain/repository/vo/GetSymptomVO.java
  meongcare/src/main/java/com/meongcare/domain/symptom/presentation/SymptomController.java
  meongcare/src/main/java/com/meongcare/domain/symptom/presentation/dto/request/DeleteSymptomRequest.java
  meongcare/src/main/java/com/meongcare/domain/symptom/presentation/dto/request/EditSymptomRequest.java
  meongcare/src/main/java/com/meongcare/domain/symptom/presentation/dto/request/SaveSymptomRequest.java
  meongcare/src/main/java/com/meongcare/domain/symptom/presentation/dto/response/GetSymptomResponse.java
  meongcare/src/main/java/com/meongcare/infra/config/QuerydslConfig.java
  meongcare/src/main/java/com/meongcare/infra/image/ImageDirectory.java
  meongcare/src/main/java/com/meongcare/infra/image/ImageHandler.java
  meongcare/src/main/java/com/meongcare/infra/image/s3/ImageHandlerS3.java
  meongcare/src/main/java/com/meongcare/infra/image/s3/S3Api.java
Labels: feat

#8 feat: 테스트 서버 CI/CD 자동화
  .github/workflows/cicd-dev.yml
  meongcare/Dockerfile
  meongcare/build.gradle
  meongcare/docker-compose.yml
  meongcare/src/main/java/com/meongcare/MeongcareApplication.java
Labels: feat

#10 feat: 진료 기록 API
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/application/MedicalRecordService.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/domain/entity/MedicalRecord.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/domain/repository/MedicalRecordQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/domain/repository/MedicalRecordRepository.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/domain/repository/vo/GetMedicalRecordsVo.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/MedicalRecordController.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/request/PutMedicalRecordRequestDto.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/request/SaveMedicalRecordRequestDto.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/response/GetMedicalRecordResponseDto.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/response/GetMedicalRecordsResponseDto.java
  meongcare/src/main/java/com/meongcare/infra/image/ImageDirectory.java
Labels: feat

#12 feat: 몸무게 주별, 월별 조회 및 몸무게 업데이트 API
  meongcare/src/main/java/com/meongcare/common/util/LocalDateTimeUtils.java
  meongcare/src/main/java/com/meongcare/domain/dog/domain/entity/Dog.java
  meongcare/src/main/java/com/meongcare/domain/weight/application/WeightService.java
  meongcare/src/main/java/com/meongcare/domain/weight/domain/entity/Weight.java
  meongcare/src/main/java/com/meongcare/domain/weight/domain/repository/WeightQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/weight/domain/repository/WeightRepository.java
  meongcare/src/main/java/com/meongcare/domain/weight/domain/repository/vo/GetMonthWeightVO.java
  meongcare/src/main/java/com/meongcare/domain/weight/domain/repository/vo/GetWeekWeightVO.java
  meongcare/src/main/java/com/meongcare/domain/weight/presentation/WeightController.java
  meongcare/src/main/java/com/meongcare/domain/weight/presentation/dto/response/GetWeightMonthResponse.java
  meongcare/src/main/java/com/meongcare/domain/weight/presentation/dto/response/GetWeightWeekResponse.java
  meongcare/src/main/java/com/meongcare/infra/config/S3Config.java
Labels: feat

#14 docs: Swagger(openapi) 설정
  meongcare/build.gradle
  meongcare/src/main/java/com/meongcare/domain/auth/presentation/controller/AuthController.java
  meongcare/src/main/java/com/meongcare/domain/auth/presentation/dto/request/LoginRequestDto.java
  meongcare/src/main/java/com/meongcare/domain/auth/presentation/dto/response/LoginResponseDto.java
  meongcare/src/main/java/com/meongcare/domain/auth/presentation/dto/response/ReissueResponseDto.java
  meongcare/src/main/java/com/meongcare/domain/dog/presentation/controller/DogController.java
  meongcare/src/main/java/com/meongcare/domain/dog/presentation/dto/request/SaveDogRequestDto.java
  meongcare/src/main/java/com/meongcare/domain/excreta/presentation/ExcretaController.java
  meongcare/src/main/java/com/meongcare/domain/excreta/presentation/dto/response/GetExcretaResponse.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/MedicalRecordController.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/request/PutMedicalRecordRequestDto.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/request/SaveMedicalRecordRequestDto.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/response/GetMedicalRecordResponseDto.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/response/GetMedicalRecordsResponseDto.java
  meongcare/src/main/java/com/meongcare/domain/symptom/presentation/SymptomController.java
  meongcare/src/main/java/com/meongcare/domain/symptom/presentation/dto/request/EditSymptomRequest.java
  meongcare/src/main/java/com/meongcare/domain/symptom/presentation/dto/request/SaveSymptomRequest.java
  meongcare/src/main/java/com/meongcare/domain/symptom/presentation/dto/response/GetSymptomResponse.java
  meongcare/src/main/java/com/meongcare/domain/weight/application/WeightService.java
  meongcare/src/main/java/com/meongcare/domain/weight/presentation/WeightController.java
  meongcare/src/main/java/com/meongcare/domain/weight/presentation/dto/response/GetMonthWeightResponse.java
  meongcare/src/main/java/com/meongcare/domain/weight/presentation/dto/response/GetWeekWeightResponse.java
Labels: docs

#17 refactor: 디폴트 값 지정을 통해 생성일자 입력
  meongcare/src/main/java/com/meongcare/common/BaseEntity.java
  meongcare/src/main/java/com/meongcare/domain/weight/domain/entity/Weight.java
  meongcare/src/main/java/com/meongcare/domain/weight/domain/repository/WeightJdbcRepository.java
Labels: refactor

#19 feat: CORS 설정 & JWT Filter 구현
  meongcare/.gitignore
  meongcare/build.gradle
  meongcare/src/main/java/com/meongcare/MeongcareApplication.java
  meongcare/src/main/java/com/meongcare/common/jwt/JwtAuthenticationFilter.java
  meongcare/src/main/java/com/meongcare/common/jwt/JwtService.java
  meongcare/src/main/java/com/meongcare/common/jwt/JwtValidation.java
  meongcare/src/main/java/com/meongcare/domain/auth/presentation/controller/AuthController.java
  meongcare/src/main/java/com/meongcare/domain/dog/presentation/controller/DogController.java
  meongcare/src/main/java/com/meongcare/domain/excreta/presentation/ExcretaController.java
  meongcare/src/main/java/com/meongcare/domain/symptom/presentation/SymptomController.java
  meongcare/src/main/java/com/meongcare/domain/weight/presentation/WeightController.java
  meongcare/src/main/java/com/meongcare/infra/config/SecurityConfig.java
  meongcare/src/main/java/com/meongcare/infra/config/WebConfig.java
Labels: feat

#23 fix: 존재하지 않는 클래스 의존성 제거 #22
  meongcare/src/main/java/com/meongcare/infra/config/SecurityConfig.java
Labels: fix

#21 feat: 나의정보 & 강아지 API 구현
  meongcare/src/main/java/com/meongcare/domain/auth/application/AuthService.java
  meongcare/src/main/java/com/meongcare/domain/auth/presentation/controller/AuthController.java
  meongcare/src/main/java/com/meongcare/domain/auth/presentation/dto/request/LoginRequest.java
  meongcare/src/main/java/com/meongcare/domain/auth/presentation/dto/response/LoginResponse.java
  meongcare/src/main/java/com/meongcare/domain/auth/presentation/dto/response/ReissueResponse.java
  meongcare/src/main/java/com/meongcare/domain/dog/application/DogService.java
  meongcare/src/main/java/com/meongcare/domain/dog/domain/DogWeightRepository.java
  meongcare/src/main/java/com/meongcare/domain/dog/domain/entity/Dog.java
  meongcare/src/main/java/com/meongcare/domain/dog/domain/entity/DogWeight.java
  meongcare/src/main/java/com/meongcare/domain/dog/domain/entity/Sex.java
  meongcare/src/main/java/com/meongcare/domain/dog/presentation/controller/DogController.java
  meongcare/src/main/java/com/meongcare/domain/dog/presentation/dto/request/PutDogRequest.java
  meongcare/src/main/java/com/meongcare/domain/dog/presentation/dto/request/SaveDogRequest.java
  meongcare/src/main/java/com/meongcare/domain/dog/presentation/dto/response/GetDogResponse.java
  meongcare/src/main/java/com/meongcare/domain/dog/presentation/dto/response/GetDogsResponse.java
  meongcare/src/main/java/com/meongcare/domain/dog/service/DogService.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/application/MedicalRecordService.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/domain/entity/MedicalRecord.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/MedicalRecordController.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/request/PutMedicalRecordRequest.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/request/SaveMedicalRecordRequest.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/response/GetMedicalRecordResponse.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/response/GetMedicalRecordsResponse.java
  meongcare/src/main/java/com/meongcare/domain/member/application/MemberService.java
  meongcare/src/main/java/com/meongcare/domain/member/domain/entity/Member.java
  meongcare/src/main/java/com/meongcare/domain/member/domain/entity/Provider.java
  meongcare/src/main/java/com/meongcare/domain/member/domain/repository/MemberRepository.java
  meongcare/src/main/java/com/meongcare/domain/member/presentation/controller/MemberController.java
  meongcare/src/main/java/com/meongcare/domain/member/presentation/dto/response/GetProfileResponse.java
  meongcare/src/main/java/com/meongcare/domain/weight/application/WeightService.java
  meongcare/src/main/java/com/meongcare/domain/weight/domain/entity/Weight.java
  meongcare/src/main/java/com/meongcare/infra/image/ImageDirectory.java
Labels: feat

#26 feat: 공지사항 API 구현
  meongcare/src/main/java/com/meongcare/domain/auth/application/AuthService.java
  meongcare/src/main/java/com/meongcare/domain/auth/presentation/controller/AuthController.java
  meongcare/src/main/java/com/meongcare/domain/dog/application/DogService.java
  meongcare/src/main/java/com/meongcare/domain/dog/presentation/controller/DogController.java
  meongcare/src/main/java/com/meongcare/domain/notice/application/NoticeService.java
  meongcare/src/main/java/com/meongcare/domain/notice/domain/entity/Notice.java
  meongcare/src/main/java/com/meongcare/domain/notice/domain/entity/NoticeType.java
  meongcare/src/main/java/com/meongcare/domain/notice/domain/repository/NoticeQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/notice/domain/repository/NoticeRepository.java
  meongcare/src/main/java/com/meongcare/domain/notice/domain/repository/vo/GetNoticesVO.java
  meongcare/src/main/java/com/meongcare/domain/notice/presentation/controller/NoticeController.java
  meongcare/src/main/java/com/meongcare/domain/notice/presentation/dto/request/PatchNoticeRequest.java
  meongcare/src/main/java/com/meongcare/domain/notice/presentation/dto/request/SaveNoticeRequest.java
  meongcare/src/main/java/com/meongcare/domain/notice/presentation/dto/response/GetNoticesResponse.java
  meongcare/src/main/java/com/meongcare/infra/config/SecurityConfig.java
Labels: feat

#28 feat: 사료 API 기능 구현
  meongcare/src/main/java/com/meongcare/common/util/LocalDateTimeUtils.java
  meongcare/src/main/java/com/meongcare/domain/excreta/presentation/dto/response/GetExcretaResponse.java
  meongcare/src/main/java/com/meongcare/domain/feed/application/FeedService.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/entity/Feed.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/entity/FeedRecord.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/FeedController.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/request/ChangeFeedRequest.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/request/SaveFeedRequest.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/GetFeedRecordsResponse.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/GetFeedResponse.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/GetFeedsPartResponse.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/GetFeedsResponse.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/vo/GetFeedRecordsPartVO.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/vo/GetFeedRecordsVO.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/vo/GetFeedsVO.java
  meongcare/src/main/java/com/meongcare/infra/image/ImageDirectory.java
Labels: feat

#29 feat: 대소변 상세조회 API
  meongcare/src/main/java/com/meongcare/common/util/LocalDateTimeUtils.java
  meongcare/src/main/java/com/meongcare/domain/excreta/application/ExcretaService.java
  meongcare/src/main/java/com/meongcare/domain/excreta/presentation/ExcretaController.java
  meongcare/src/main/java/com/meongcare/domain/excreta/presentation/dto/response/GetExcretaDetailResponse.java
Labels: feat

#33 feat: 테스트 서버 배포 Slack 알림 기능 구현
  .github/workflows/cicd-dev.yml
Labels: feat

#34 feat: 영양제 API
  meongcare/src/main/java/com/meongcare/MeongcareApplication.java
  meongcare/src/main/java/com/meongcare/common/DateTimePattern.java
  meongcare/src/main/java/com/meongcare/common/util/LocalDateTimeUtils.java
  meongcare/src/main/java/com/meongcare/domain/dog/application/DogService.java
  meongcare/src/main/java/com/meongcare/domain/dog/presentation/controller/DogController.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/MedicalRecordController.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/presentation/dto/response/GetMedicalRecordsResponse.java
  meongcare/src/main/java/com/meongcare/domain/member/application/MemberService.java
  meongcare/src/main/java/com/meongcare/domain/member/domain/repository/MemberRepository.java
  meongcare/src/main/java/com/meongcare/domain/member/presentation/controller/MemberController.java
  meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsScheduler.java
  meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsService.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/entity/Supplements.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/entity/SupplementsRecord.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/entity/SupplementsTime.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRecordJdbcRepository.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRecordQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRecordRepository.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRepository.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsTimeQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsTimeRepository.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/vo/GetSupplementsAndTimeVO.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/vo/GetSupplementsRoutineVO.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/vo/GetSupplementsRoutineWithoutStatusVO.java
  meongcare/src/main/java/com/meongcare/domain/supplements/presentation/controller/SupplementsController.java
  meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/request/SaveSupplementsRequest.java
  meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/response/GetSupplementsRateResponse.java
  meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/response/GetSupplementsResponse.java
  meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/response/GetSupplementsRoutineResponse.java
  meongcare/src/main/java/com/meongcare/infra/image/ImageDirectory.java
Labels: feat
