Repository Semoban/meongcare-back, pull requests merged in 2024-01, with the labels that each got.

#70 fix: 영양제 저장 요청값 역직렬화 안되는 문제 해결
  meongcare/src/main/java/com/meongcare/domain/supplements/presentation/controller/SupplementsController.java
  meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/request/SaveSupplementsRequest.java
  meongcare/src/main/java/com/meongcare/infra/config/SecurityConfig.java
  meongcare/src/main/resources/application-local.yml
Labels: fix

#72 [FIX] 영양제 등록 요청 미디어 타입 설정
  meongcare/src/main/java/com/meongcare/domain/supplements/presentation/controller/SupplementsController.java
Labels: refactor, fix

#78 feat: 사료 상세 조회 API 구현 및 사료 조회시 이미지 필드 추가, fix: 사료 변경 시 null 처리
  meongcare/src/main/java/com/meongcare/common/error/exception/BaseException.java
  meongcare/src/main/java/com/meongcare/domain/feed/application/FeedService.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/vo/GetFeedDetailVO.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/vo/GetFeedRecordsVO.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/vo/GetFeedsVO.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/FeedController.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/GetFeedDetailResponse.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/GetFeedRecordsResponse.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/GetFeedsResponse.java
Labels: feat, fix

#80 feat: 사용자 정보 조회 알림 설정 여부 필드 추가 (#79)
  meongcare/src/main/java/com/meongcare/domain/member/application/MemberService.java
  meongcare/src/main/java/com/meongcare/domain/member/presentation/dto/response/GetProfileResponse.java
Labels: feat

#82 feat: supplementsId 응답 추가 (#81)
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRecordQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsTimeQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/vo/GetSupplementsRoutineVO.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/vo/GetSupplementsRoutineWithoutStatusVO.java
  meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/response/GetSupplementsInfoResponse.java
  meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/response/GetSupplementsRoutineResponse.java
Labels: feat

#84 feat: feedId 필드 추가
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/vo/GetFeedRecordsVO.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/GetFeedRecordsResponse.java
Labels: feat

#93 feat: 최초로그인 여부 추가 (#92)
  meongcare/src/main/java/com/meongcare/domain/auth/application/AuthService.java
  meongcare/src/main/java/com/meongcare/domain/auth/presentation/dto/response/LoginResponse.java
Labels: feat

#97 feat: 사료 성분 기타 필드 추가
  meongcare/src/main/java/com/meongcare/domain/feed/domain/entity/Feed.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/vo/GetFeedDetailVO.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/request/EditFeedRequest.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/request/SaveFeedRequest.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/GetFeedDetailResponse.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/response/GetFeedResponse.java
Labels: feat

#95 [FIX] 로그인 로직 수정, 검증 에러 응답 수정
  meongcare/src/main/java/com/meongcare/common/error/GlobalExceptionHandler.java
  meongcare/src/main/java/com/meongcare/common/jwt/JwtAuthenticationFilter.java
  meongcare/src/main/java/com/meongcare/common/jwt/JwtService.java
  meongcare/src/main/java/com/meongcare/domain/auth/application/AuthService.java
  meongcare/src/main/java/com/meongcare/domain/auth/presentation/dto/request/LoginRequest.java
  meongcare/src/main/java/com/meongcare/domain/dog/domain/entity/Dog.java
  meongcare/src/main/java/com/meongcare/domain/dog/presentation/controller/DogController.java
  meongcare/src/main/java/com/meongcare/domain/dog/presentation/dto/request/SaveDogRequest.java
  meongcare/src/main/java/com/meongcare/domain/member/domain/entity/Member.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/entity/Supplements.java
  meongcare/src/main/java/com/meongcare/domain/supplements/presentation/controller/SupplementsController.java
  meongcare/src/main/java/com/meongcare/domain/supplements/presentation/dto/request/SaveSupplementsRequest.java
  meongcare/src/main/java/com/meongcare/infra/config/SecurityConfig.java
Labels: fix

#101 [FEAT] 탈퇴 회원 분리 보관, 탈퇴 후 90일간 로그인 금지 #96
  meongcare/build.gradle
  meongcare/src/main/java/com/meongcare/common/constants/BusinessLogicConstants.java
  meongcare/src/main/java/com/meongcare/common/error/ErrorCode.java
  meongcare/src/main/java/com/meongcare/common/error/GlobalExceptionHandler.java
  meongcare/src/main/java/com/meongcare/common/error/exception/UnauthorizedException.java
  meongcare/src/main/java/com/meongcare/common/jwt/JwtAuthenticationFilter.java
  meongcare/src/main/java/com/meongcare/domain/auth/application/AuthService.java
  meongcare/src/main/java/com/meongcare/domain/dog/application/DogService.java
  meongcare/src/main/java/com/meongcare/domain/dog/domain/DogRepository.java
  meongcare/src/main/java/com/meongcare/domain/dog/domain/entity/Dog.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/application/MedicalRecordService.java
  meongcare/src/main/java/com/meongcare/domain/member/application/MemberService.java
  meongcare/src/main/java/com/meongcare/domain/member/application/RevokeMemberScheduler.java
  meongcare/src/main/java/com/meongcare/domain/member/domain/entity/Member.java
  meongcare/src/main/java/com/meongcare/domain/member/domain/entity/RevokeMember.java
  meongcare/src/main/java/com/meongcare/domain/member/domain/repository/MemberRepository.java
  meongcare/src/main/java/com/meongcare/domain/member/domain/repository/RevokeMemberRepository.java
  meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsService.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/entity/SupplementsTime.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsTimeRepository.java
  meongcare/src/main/java/com/meongcare/domain/supplements/presentation/controller/SupplementsController.java
Labels: feat

#107 [FIX] getById() 삭제된 데이터는 조회 안되게 수정 (#106)
  meongcare/src/main/java/com/meongcare/domain/dog/application/DogService.java
  meongcare/src/main/java/com/meongcare/domain/dog/domain/DogRepository.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/application/MedicalRecordService.java
  meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsService.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRepository.java
Labels: fix

#110 알림 메세지 수정, 로그인 시 fcm 확인 #108
  meongcare/src/main/java/com/meongcare/domain/auth/application/AuthService.java
  meongcare/src/main/java/com/meongcare/domain/member/domain/entity/Member.java
  meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsScheduler.java
  meongcare/src/main/java/com/meongcare/infra/message/MessageHandler.java
  meongcare/src/main/java/com/meongcare/infra/message/firebase/MessageHandlerFirebase.java
Labels: feat, fix

#111 사료 활성화 로직 수정
  meongcare/src/main/java/com/meongcare/domain/feed/application/FeedService.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/entity/Feed.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/entity/FeedRecord.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/FeedController.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/dto/request/SaveFeedRequest.java
Labels: feat

#113 사료 중단 API
  meongcare/src/main/java/com/meongcare/domain/feed/application/FeedService.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/presentation/FeedController.java
Labels: feat

#116 사료 기록 삭제 쿼리 수정
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordQueryRepository.java
Labels: fix

#117 [REFACTOR] 메서드 이름 변경 #114
  meongcare/src/main/java/com/meongcare/common/BaseEntity.java
  meongcare/src/main/java/com/meongcare/domain/dog/application/DogService.java
  meongcare/src/main/java/com/meongcare/domain/dog/domain/DogRepository.java
  meongcare/src/main/java/com/meongcare/domain/member/application/MemberService.java
  meongcare/src/main/java/com/meongcare/domain/member/domain/entity/Member.java
  meongcare/src/main/java/com/meongcare/domain/member/domain/repository/MemberRepository.java
  meongcare/src/main/java/com/meongcare/domain/notice/application/NoticeService.java
  meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsService.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRepository.java
  meongcare/src/main/java/com/meongcare/domain/supplements/presentation/controller/SupplementsController.java
Labels: refactor

#118 fix: 메서드 이름 변경
  meongcare/src/main/java/com/meongcare/common/jwt/JwtAuthenticationFilter.java
  meongcare/src/main/java/com/meongcare/domain/dog/application/DogService.java
  meongcare/src/main/java/com/meongcare/domain/feed/application/FeedService.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/application/MedicalRecordService.java
Labels: fix

#119 [FEAT] Logback으로 로그 저장, sentry 모니터링 #90
  meongcare/build.gradle
  meongcare/src/main/java/com/meongcare/common/error/ErrorCode.java
  meongcare/src/main/java/com/meongcare/common/error/GlobalExceptionHandler.java
  meongcare/src/main/java/com/meongcare/common/error/exception/clientError/BadRequestException.java
  meongcare/src/main/java/com/meongcare/common/error/exception/clientError/EntityNotFoundException.java
  meongcare/src/main/java/com/meongcare/common/error/exception/clientError/InvalidTokenException.java
  meongcare/src/main/java/com/meongcare/common/error/exception/clientError/UnauthorizedException.java
  meongcare/src/main/java/com/meongcare/common/error/exception/serverError/FailedFileUploadException.java
  meongcare/src/main/java/com/meongcare/common/error/exception/serverError/InternalServerException.java
  meongcare/src/main/java/com/meongcare/common/error/exception/serverError/MessageException.java
  meongcare/src/main/java/com/meongcare/common/jwt/JwtService.java
  meongcare/src/main/java/com/meongcare/common/jwt/JwtValidateArgumentResolver.java
  meongcare/src/main/java/com/meongcare/domain/auth/application/AuthService.java
  meongcare/src/main/java/com/meongcare/domain/dog/domain/DogRepository.java
  meongcare/src/main/java/com/meongcare/domain/excreta/domain/repository/ExcretaRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/application/FeedService.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRepository.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/domain/repository/MedicalRecordRepository.java
  meongcare/src/main/java/com/meongcare/domain/member/application/MemberService.java
  meongcare/src/main/java/com/meongcare/domain/member/domain/repository/MemberRepository.java
  meongcare/src/main/java/com/meongcare/domain/notice/domain/repository/NoticeRepository.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRecordRepository.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRepository.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsTimeRepository.java
  meongcare/src/main/java/com/meongcare/domain/symptom/domain/repository/SymptomRepository.java
  meongcare/src/main/java/com/meongcare/infra/image/s3/ImageHandlerS3.java
  meongcare/src/main/java/com/meongcare/infra/message/firebase/MessageHandlerFirebase.java
  meongcare/src/main/resources/logback-spring.xml
Labels: feat

#122 사료 섭취 중단 후 사료 변경 시도 시 처리가능하도록 변경
  meongcare/src/main/java/com/meongcare/domain/feed/application/FeedService.java
Labels: feat
