Repository Semoban/meongcare-back, pull requests merged in 2024-02, with the labels that each got.

#124 [FEAT] 잘못된 파라미터 요청 처리 #123
  meongcare/src/main/java/com/meongcare/common/error/ErrorCode.java
  meongcare/src/main/java/com/meongcare/common/error/ErrorResponse.java
  meongcare/src/main/java/com/meongcare/common/error/GlobalExceptionHandler.java
  meongcare/src/main/java/com/meongcare/common/jwt/JwtAuthenticationFilter.java
Labels: feat

#127 알림 이벤트 발행 및 비동기 처리, 알림 전송 실패 시 DB에 저장
  meongcare/src/main/java/com/meongcare/common/event/EventListener.java
  meongcare/src/main/java/com/meongcare/domain/notifciation/domain/dto/FcmNotificationDTO.java
  meongcare/src/main/java/com/meongcare/domain/notifciation/domain/entity/NotificationRecord.java
  meongcare/src/main/java/com/meongcare/domain/notifciation/domain/entity/NotificationType.java
  meongcare/src/main/java/com/meongcare/domain/notifciation/domain/repository/NotificationRecordRepository.java
  meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsScheduler.java
  meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsService.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/vo/GetAlarmSupplementsVO.java
  meongcare/src/main/java/com/meongcare/infra/message/MessageHandler.java
  meongcare/src/main/java/com/meongcare/infra/message/firebase/MessageHandlerFirebase.java
Labels: feat, refactor

#129 조회 컬럼 수정
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRecordQueryRepository.java
Labels: fix

#130 [FEAT] 강아지 삭제 시 관련 정보 삭제 #100
  meongcare/src/main/java/com/meongcare/domain/dog/application/DogService.java
  meongcare/src/main/java/com/meongcare/domain/excreta/domain/repository/ExcretaQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/application/MedicalRecordService.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/domain/entity/MedicalRecord.java
  meongcare/src/main/java/com/meongcare/domain/medicalrecord/domain/repository/MedicalRecordQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/member/application/MemberService.java
  meongcare/src/main/java/com/meongcare/domain/supplements/application/SupplementsService.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/entity/SupplementsRecord.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsRecordQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/supplements/domain/repository/SupplementsTimeQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/symptom/domain/repository/SymptomQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/weight/domain/repository/WeightQueryRepository.java
Labels: feat

#132 사료 기록 하나 남은거 삭제 시, 사료 삭제 처리 및 ID 기반 조회 조건 추가
  meongcare/src/main/java/com/meongcare/domain/excreta/domain/repository/ExcretaRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/application/FeedService.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRecordRepository.java
  meongcare/src/main/java/com/meongcare/domain/feed/domain/repository/FeedRepository.java
  meongcare/src/main/java/com/meongcare/domain/symptom/domain/repository/SymptomRepository.java
Labels: feat

#135 [FIX]운영 서버 로그 모니터링 설정 변경 #134
  meongcare/src/main/resources/logback-spring.xml
Labels: docs, fix

#138 알림 실패 시 재시도하는 스케줄러 및 기능 추가
  meongcare/src/main/java/com/meongcare/domain/notifciation/application/NotificationScheduler.java
  meongcare/src/main/java/com/meongcare/domain/notifciation/application/NotificationService.java
  meongcare/src/main/java/com/meongcare/domain/notifciation/domain/entity/NotificationRecord.java
  meongcare/src/main/java/com/meongcare/domain/notifciation/domain/repository/NotificationRecordQueryRepository.java
  meongcare/src/main/java/com/meongcare/infra/message/firebase/MessageHandlerFirebase.java
Labels: feat

#142 feat: logback-spring.xml 프로필 설정 변경
  meongcare/src/main/resources/logback-spring.xml
Labels: feat

#144 WeightService 테스트 코드 작성
  meongcare/build.gradle
  meongcare/src/main/java/com/meongcare/common/error/ErrorCode.java
  meongcare/src/main/java/com/meongcare/domain/dog/application/DogService.java
  meongcare/src/main/java/com/meongcare/domain/excreta/application/ExcretaService.java
  meongcare/src/main/java/com/meongcare/domain/symptom/application/SymptomService.java
  meongcare/src/main/java/com/meongcare/domain/weight/application/WeightService.java
  meongcare/src/main/java/com/meongcare/domain/weight/domain/repository/WeightQueryRepository.java
  meongcare/src/main/java/com/meongcare/domain/weight/presentation/dto/response/GetMonthWeightResponse.java
  meongcare/src/main/java/com/meongcare/domain/weight/presentation/dto/response/GetWeekWeightResponse.java
  meongcare/src/test/java/com/meongcare/domain/weight/application/WeightServiceTest.java
Labels: Test

#148 [FIX] fcm 로그인 시 삭제 #147
  meongcare/src/main/java/com/meongcare/common/jwt/JwtAuthenticationFilter.java
  meongcare/src/main/java/com/meongcare/common/jwt/JwtValidateArgumentResolver.java
  meongcare/src/main/java/com/meongcare/domain/auth/application/AuthService.java
  meongcare/src/main/java/com/meongcare/domain/auth/presentation/controller/AuthController.java
  meongcare/src/main/java/com/meongcare/domain/dog/application/DogService.java
  meongcare/src/main/java/com/meongcare/domain/dog/presentation/controller/DogController.java
  meongcare/src/main/java/com/meongcare/domain/member/application/MemberService.java
  meongcare/src/main/java/com/meongcare/domain/member/domain/entity/Member.java
  meongcare/src/main/java/com/meongcare/domain/member/domain/repository/MemberRepository.java
  meongcare/src/main/java/com/meongcare/domain/member/presentation/controller/MemberController.java
  meongcare/src/main/java/com/meongcare/domain/notifciation/application/NotificationService.java
  meongcare/src/main/java/com/meongcare/domain/notifciation/domain/entity/NotificationRecord.java
  meongcare/src/main/java/com/meongcare/infra/message/firebase/MessageHandlerFirebase.java
Labels: fix

#150 refactor: member로 이름 변경
  meongcare/src/main/java/com/meongcare/common/jwt/JwtService.java
  meongcare/src/main/java/com/meongcare/domain/auth/application/AuthService.java
  meongcare/src/main/java/com/meongcare/domain/notifciation/domain/dto/FcmNotificationDTO.java
Labels: refactor
